class Catalogo:
    VALORES_CONSTANTES = "VALORES_CONSTANTES"
    ESTADO_USUARIO = "ESTADO_USUARIO"
    TIPO_DOCUMENTO = "TIPO_DOCUMENTO"
    SEXO = "SEXO"
    PRIORIDAD = "PRIORIDAD"
    MEDICO = "MEDICO"
    TIPO_INSPECCION = "TIPO_INSPECCION"
    CONECTADO = "CONECTADO"
    ESTADO = "ESTADO_EQUIPO"
    FUNCIONA = "FUNCIONA"
    TIPO_SENALIZACION = "TIPO_SENALIZACION"
    ESTADO_CAPACITACION = "ESTADO_CAPACITACION"
    TIPO_CAPACITACION = "TIPO_CAPACITACION"
    ESTADO_EXTINTOR = "ESTADO_EXTINTOR"
    TIPO_CAPACIDAD = "TIPO_CAPACIDAD"
    TIPO_EXTINTOR = "TIPO_EXTINTOR"
    PABELLON = "PABELLON"
    GRADO_ESTUDIOS = "GRADO_ESTUDIOS"
    TIPO_SANGRE = "TIPO_SANGRE"
    TIPO_ALTERNATIVA = "TIPO_ALTERNATIVA"

    def __init__(self):
        raise RuntimeError("Catalogo is a constants-only class")
